name: Validate JSONs
on:
  pull_request:
    paths:
      - 'lang/*.json'
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./lang/en.json
          INPUT_JSONS: ./lang/cn.json,./lang/cs.json,./lang/de.json,./lang/en.json,./lang/es.json,./lang/fr.json,./lang/ja.json,./lang/pl.json,./lang/pt-BR.json,./lang/sv.json,./lang/zh-TW.json
